language: node_js
node_js:
  - "6"
  - "8"
  - "9"
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
notifications:
  email: false
